# Generated by Django 2.0.1 on 2018-02-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wpisz nazwe kategorii')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazyn_text', models.CharField(max_length=50, verbose_name='Wpisz nazwe magazynu')),
            ],
            options={
                'verbose_name': 'Magazyny',
                'verbose_name_plural': 'Magazyny',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_text', models.CharField(max_length=200, verbose_name='Wpisz nazwe produktu')),
                ('dodaj_grafike', models.ImageField(upload_to='', verbose_name='Dodaj grafike')),
                ('ilosc', models.IntegerField(default=1)),
                ('jednostka', models.CharField(default='szt.', max_length=10, verbose_name='Jednostka')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Category', verbose_name='Wybierz kategorie')),
                ('magazyn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Magazyn', verbose_name='Wybierz magazyn')),
                ('user', models.ForeignKey(default='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uzytkownik')),
            ],
            options={
                'verbose_name': 'Produkty',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Product_Change_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date_time', models.DateTimeField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Product', verbose_name='')),
            ],
            options={
                'verbose_name': 'Logi',
                'verbose_name_plural': 'Logi',
            },
        ),
    ]
